In [37]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np

# Plotting library
from matplotlib import pyplot

# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
from scipy.io import loadmat


import pandas as pd

#esta tabulate nos sirve para hacer tablas
from tabulate import tabulate

# Librerias para graficación (trazado de gráficos)
from matplotlib import pyplot
# tells matplotlib to embed plots within the notebook

#Para separa el 20% y 80%
from sklearn.model_selection import train_test_split
%matplotlib inline

# Red nueronal

In [38]:
dataset = pd.read_csv('BirdSpecies_dataset.csv', delimiter=',')


# dataset = pd.read_csv('OnlineNewsPopularity.csv', delimiter=',')
#para usarlo a travez de google colab
dataset = dataset.sample(n=20000, random_state=42)

dataset

BodyLength  Wingspan  Weight  PlumageColorHead  PlumageColorBack  \
6868        5.501     0.398   6.846             0.805             0.325   
24016       6.444     8.711   1.309             0.890             8.843   
9668        0.273     5.533   4.428             5.289             5.419   
13640       8.912     1.691   9.683             2.847             2.258   
14018       3.513     8.207   6.038             3.123             0.663   
...           ...       ...     ...               ...               ...   
3791        8.214     8.988   0.101             2.497             5.954   
23445       7.663     6.968   8.822             7.402             9.460   
14154       4.681     7.425   5.612             8.761             8.511   
2786        3.211     6.911   3.306             4.846             7.787   
9259        1.864     6.024   9.642             0.929             9.840   

       PlumageColorBelly  PlumageColorWings  PlumageColorTail  BeakLength  \
6868               7.072              0.497             6.905       9.287   
24016              7.327              3.221             8.431       6.331   
9668               0.798              8.739             5.877       0.304   
13640              2.951              6.249             9.674       4.296   
14018              2.423              4.136             1.694       0.988   
...                  ...                ...               ...         ...   
3791               7.443              7.401             3.670       9.307   
23445              2.592              5.008             7.041       9.135   
14154              5.891              5.465             8.920       8.096   
2786               4.685              9.147             3.835       7.194   
9259               8.300              6.191             0.574       2.066   

       BeakWidth  ...  SeedDispersalRole  InterspecificInteraction  \
6868       1.472  ...              5.650                     2.046   
24016      2.556  ...              0.635                     8.539   
9668       1.938  ...              2.613                     7.502   
13640      1.164  ...              0.250                     6.526   
14018      5.227  ...              9.547                     8.516   
...          ...  ...                ...                       ...   
3791       2.224  ...              8.079                     2.908   
23445      5.077  ...              9.649                     7.073   
14154      3.858  ...              7.815                     2.034   
2786       2.015  ...              8.205                     2.636   
9259       1.835  ...              3.082                     9.056   

       IntraspecificInteraction  LearningAbility  ToolUse  ParentalCareLevel  \
6868                      9.993            1.066    0.567              7.668   
24016                     8.770            9.193    2.581              5.422   
9668                      6.780            6.684    2.246              9.646   
13640                     4.387            7.123    2.318              1.063   
14018                     7.609            0.631    7.271              4.115   
...                         ...              ...      ...                ...   
3791                      3.623            6.811    7.126              5.741   
23445                     2.362            1.960    4.795              0.132   
14154                     7.907            1.465    4.242              2.601   
2786                      1.068            1.729    9.482              4.961   
9259                      2.841            1.363    7.602              7.336   

       BathingBehavior  GroomingBehavior  FlightSpeed  SpeciesClass  
6868             1.344             7.939        8.780             1  
24016            7.256             7.390        3.678             5  
9668             5.405             4.260        2.110             3  
13640            3.434             6.701        4.200             3  
14018            8.989       

## Tratamiento de datos

vamos a eliminar las columnas de nuestro dataset que no necesitamos, en este caso la direccion de url:

In [61]:
#dropeamos la columna de url
dataset = dataset.drop(['ColorVision','NocturnalVision'], axis=1)

dataset

BodyLength  Wingspan  Weight  PlumageColorHead  PlumageColorBack  \
6868        5.501     0.398   6.846             0.805             0.325   
24016       6.444     8.711   1.309             0.890             8.843   
9668        0.273     5.533   4.428             5.289             5.419   
13640       8.912     1.691   9.683             2.847             2.258   
14018       3.513     8.207   6.038             3.123             0.663   
...           ...       ...     ...               ...               ...   
3791        8.214     8.988   0.101             2.497             5.954   
23445       7.663     6.968   8.822             7.402             9.460   
14154       4.681     7.425   5.612             8.761             8.511   
2786        3.211     6.911   3.306             4.846             7.787   
9259        1.864     6.024   9.642             0.929             9.840   

       PlumageColorBelly  PlumageColorWings  PlumageColorTail  BeakLength  \
6868               7.072              0.497             6.905       9.287   
24016              7.327              3.221             8.431       6.331   
9668               0.798              8.739             5.877       0.304   
13640              2.951              6.249             9.674       4.296   
14018              2.423              4.136             1.694       0.988   
...                  ...                ...               ...         ...   
3791               7.443              7.401             3.670       9.307   
23445              2.592              5.008             7.041       9.135   
14154              5.891              5.465             8.920       8.096   
2786               4.685              9.147             3.835       7.194   
9259               8.300              6.191             0.574       2.066   

       BeakWidth  ...  SeedDispersalRole  InterspecificInteraction  \
6868       1.472  ...              5.650                     2.046   
24016      2.556  ...              0.635                     8.539   
9668       1.938  ...              2.613                     7.502   
13640      1.164  ...              0.250                     6.526   
14018      5.227  ...              9.547                     8.516   
...          ...  ...                ...                       ...   
3791       2.224  ...              8.079                     2.908   
23445      5.077  ...              9.649                     7.073   
14154      3.858  ...              7.815                     2.034   
2786       2.015  ...              8.205                     2.636   
9259       1.835  ...              3.082                     9.056   

       IntraspecificInteraction  LearningAbility  ToolUse  ParentalCareLevel  \
6868                      9.993            1.066    0.567              7.668   
24016                     8.770            9.193    2.581              5.422   
9668                      6.780            6.684    2.246              9.646   
13640                     4.387            7.123    2.318              1.063   
14018                     7.609            0.631    7.271              4.115   
...                         ...              ...      ...                ...   
3791                      3.623            6.811    7.126              5.741   
23445                     2.362            1.960    4.795              0.132   
14154                     7.907            1.465    4.242              2.601   
2786                      1.068            1.729    9.482              4.961   
9259                      2.841            1.363    7.602              7.336   

       BathingBehavior  GroomingBehavior  FlightSpeed  SpeciesClass  
6868             1.344             7.939        8.780             1  
24016            7.256             7.390        3.678             5  
9668             5.405             4.260        2.110             3  
13640            3.434             6.701        4.200             3  
14018            8.989       

## Analisis del dataset

para tener una mejor vista del los tipos de datos del dataset, hacemos un `info()`:

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 6868 to 9259
Data columns (total 59 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   BodyLength                20000 non-null  float64
 1   Wingspan                  20000 non-null  float64
 2   Weight                    20000 non-null  float64
 3   PlumageColorHead          20000 non-null  float64
 4   PlumageColorBack          20000 non-null  float64
 5   PlumageColorBelly         20000 non-null  float64
 6   PlumageColorWings         20000 non-null  float64
 7   PlumageColorTail          20000 non-null  float64
 8   BeakLength                20000 non-null  float64
 9   BeakWidth                 20000 non-null  float64
 10  BeakShape                 20000 non-null  float64
 11  BeakColor                 20000 non-null  float64
 12  LegLength                 20000 non-null  float64
 13  LegColor                  20000 non-null  float64
 14  FootType 

## Separacion del 80% de los datos para entrenamiento y 20% para pruebas

Haremos uso de la libreria `sklearn` haciendo uso de su funcion `train_test_split()`, donde recibe como parametros:

In [63]:
#separamos el 20% para test y el 80% para entrenamiento deld dataset
train_dataset, test_dataset = train_test_split(dataset, test_size=0.2, random_state=42)

# Seleccionamos las columnas para X y la columna 'shares' para y
X_test = test_dataset.drop(['SpeciesClass'], axis=1).values
y_test = test_dataset['SpeciesClass'].values
m_test = len(y_test)

# Seleccionamos las columnas para X y la columna 'shares' para y
X_train = train_dataset.drop(['SpeciesClass'], axis=1).values
y_train = train_dataset['SpeciesClass'].values
m_train = len(y_train)
# Ahora, X y y deberían contener datos numéricos del 80% del dataset



# imprimir todos las X de datos solo 10
print(X_train)
print(y_train)

[[8.172 2.631 4.667 ... 9.824 6.542 3.675]
 [4.655 5.623 8.604 ... 3.616 0.751 6.725]
 [3.717 1.057 6.497 ... 3.597 6.919 2.699]
 ...
 [9.492 4.574 8.266 ... 6.454 0.556 4.924]
 [2.556 5.462 2.754 ... 9.017 9.052 0.395]
 [6.63  7.11  7.519 ... 9.443 3.919 6.309]]
[1 5 5 ... 2 4 0]


In [64]:
print(f"el 80% de datos es:{X_train.shape[0]} y el 20% es: {X_test.shape[0]}")
print( "la totalidad de datos es: ", dataset.shape[0])

el 80% de datos es:16000 y el 20% es: 4000
la totalidad de datos es:  20000


In [65]:
### Usamos el shape para tener una imagen mas clara de las entradas

#Con esta funcion podemos obtener la cantidad de caracteristicas que estamos usando y la cantidad de ejemplos que contiene nuestra matriz.

print("la cantidad de columnas es: ", X_train.shape[1])
print("la cantidad de ejemplos es: ", X_train.shape[0])

la cantidad de columnas es:  58
la cantidad de ejemplos es:  16000


In [82]:
# En este apartado definiremos la cantidad de capas que tendra el modelo:

# - **Capa de entrada:** Es la cantidad de caracteristicas con las que cuenta el dataset.

# - **Capa oculta:** esto se define haciendo pruebas.

# - **Capa de salida:**como este modelo es de regresion lineal, se debe usar solo una capa de salida.

# Configurando parametros necesario
input_layer_size  = X_train.shape[1]  
hidden_layer_size = 9   
num_labels = 6         

print("capa de entrada es: ",input_layer_size)
print("capa de oculta es: ",hidden_layer_size)
print("capa de salida es: ",num_labels)

capa de entrada es:  58
capa de oculta es:  9
capa de salida es:  6


In [83]:
## Inicializacion de Thetas

# Inicializamos los valores de theta1 y theta2 con valores aleatorios para evitar conflictos:
# Los valores aleatorios aseguran que cada neurona pueda aprender patrones distintos, lo cual es crucial para el buen desempeño de la red.
pesos = {}
pesos['Theta1'] = np.random.rand(hidden_layer_size , input_layer_size + 1)
pesos['Theta2'] = np.random.rand(num_labels, hidden_layer_size + 1)

### Guardamos los valores de theta en nuevas variables

`.ravel()` Convertira las matrices Theta1 y Tetha2 en vectores unidimencionales.



In [84]:
# Al inicializar los pesos con valores aleatorios pequeños, se garantiza que las neuronas en una capa oculta comiencen a 
# aprender diferentes funciones. Esto aumenta la capacidad de representación de la red neuronal y permite que aprenda patrones 
# complejos en los datos de entrada. Además, la aleatorización ayuda a evitar que el algoritmo de aprendizaje se atasque en mínimos locales 
# subóptimos durante el entrenamiento.

Theta1, Theta2 = pesos['Theta1'], pesos['Theta2']


print("El tamaño de Theta1 es de: ",Theta1.ravel().shape)
print("El tamaño de Theta2 es de: ",Theta2.ravel().shape)

El tamaño de Theta1 es de:  (531,)
El tamaño de Theta2 es de:  (60,)


In [85]:
## Concadenamos Theta1 y Theta2 para formar un solo array
nn_params = np.concatenate([Theta1.ravel(), Theta2.ravel()])
print(nn_params.shape)

(591,)


In [86]:
###               Funcion de activacion

# Esta función simplemente pasa la entrada directamente a la salida sin aplicar ninguna transformación no lineal.

# def linear_activation(z):
#     return z

# def linear_gradient(z):
#     return np.ones_like(z)


import numpy as np

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=-1, keepdims=True)) # Evita problemas de estabilidad numérica
    return exp_z / np.sum(exp_z, axis=-1, keepdims=True)

def softmax_gradient(z):
    s = softmax(z)
    return s * (1 - s)  # Derivada de la función Softmax



## Funcion de costo

In [87]:
print(nn_params.shape)

(591,)


In [88]:
# permite saber si el modelo está haciendo un buen trabajo al comparar las predicciones del modelo con los valores reales que deberían ser.

# la regularización se utiliza en dos lugares principales para ayudar a prevenir el sobreajuste modificando tanto el cálculo del costo como la 
# actualización de los gradientes de los pesos. 

def nnCostFunction(nn_params,
                   input_layer_size,
                   hidden_layer_size,
                   num_labels,
                   X, y, lambda_=0.0):

    # Reshape nn_params para obtener Theta1 y Theta2
    Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                        (hidden_layer_size, (input_layer_size + 1)))
    Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                        (num_labels, (hidden_layer_size + 1)))

    m = y.size  # Número de ejemplos de entrenamiento

    J = 0
    Theta1_grad = np.zeros(Theta1.shape)
    Theta2_grad = np.zeros(Theta2.shape)

    # Propagación hacia adelante
    a1 = np.concatenate([np.ones((m, 1)), X], axis=1)
    z2 = a1.dot(Theta1.T)
    a2 = softmax(z2)
    a2 = np.concatenate([np.ones((a2.shape[0], 1)), a2], axis=1)
    z3 = a2.dot(Theta2.T)
    a3 = softmax(z3)

    # Asegurar que y tenga la forma adecuada
    y = y.reshape(-1, 1)

    #                Función de costo

    #El término de regularización se añade al costo total para penalizar los valores grandes de los pesos. 
    # Esto ayuda a mantener los pesos pequeños, lo que generalmente conduce a un modelo menos complejo y más generalizable.
    reg_term = (lambda_ / (2 * m)) * (np.sum(np.square(Theta1[:, 1:])) + np.sum(np.square(Theta2[:, 1:])))
    J = (1 / (2 * m)) * np.sum(np.square(a3 - y))
    J += reg_term

    # Retropropagación
    delta_3 = a3 - y
    delta_2 = delta_3.dot(Theta2)[:, 1:] * softmax_gradient(z2)

    Delta1 = delta_2.T.dot(a1)
    Delta2 = delta_3.T.dot(a2)

    #                    Regularización de gradientes
    # Esto se hace para asegurar que la penalización aplicada a los pesos a través de la función de costo se refleje también en la forma en que
    # los gradientes ajustan estos pesos durante el entrenamiento.
    Theta1_grad = (1 / m) * Delta1
    Theta1_grad[:, 1:] += (lambda_ / m) * Theta1[:, 1:]
    Theta2_grad = (1 / m) * Delta2
    Theta2_grad[:, 1:] += (lambda_ / m) * Theta2[:, 1:]

    # Desenrollar gradientes
    grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return J, grad

In [89]:
## Normalizacion de los datos


#Al visualizar los datos se puede observar que las caracteristicas tienen diferentes magnitudes, por lo cual se debe transformar cada valor 
# en una escala de valores similares.

def  featureNormalize(X):
    X_norm = X.copy()

    #creamos un array de ceros con una longitud igual al número de columnas en el array X. La variable mu y sigma se inicializa como este array de ceros.
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    #Creamos el promedio de cada columna de X
    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)

    sigma[sigma == 0] = 1

    #normalizamos los datos con la siguiente formula
    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma



In [90]:
X_norm, mu, sigma = featureNormalize(X_train)

In [91]:
print("Longitud de nn_params:", len(nn_params))
print("Expected size for Theta2:", (hidden_layer_size + 1) * num_labels)

Longitud de nn_params: 591
Expected size for Theta2: 60


## Calculo del costo

In [92]:
lambda_ = 10000
J, _ = nnCostFunction(nn_params, input_layer_size, hidden_layer_size, num_labels, X_norm, y_train, lambda_)
print('Costo en parametros (cargado de ex4weights): %.6f ' % J)
#print('El costo debe esta cercano a               

Costo en parametros (cargado de ex4weights): 87.706911 


## Inicializar pesos aleatorios



La matriz de pesos inicializada aleatoriamente se devuelve como salida de la función.

In [93]:
#La función randInitializeWeights que has definido es un método común para inicializar los pesos de una red neuronal 
# de manera aleatoria. Esta inicialización es crucial para asegurar que la red neuronal comience el aprendizaje con una ruptura de simetría, 
# permitiendo que las neuronas aprendan diferentes funciones.

def randInitializeWeights(L_in, L_out, epsilon_init=0.12):

    W = np.zeros((L_out, 1 + L_in))
    W = np.random.rand(L_out, 1 + L_in) * 2 * epsilon_init - epsilon_init

    return W

In [94]:
print('Inicialización de parámetros de redes neuronales...')

initial_Theta1 = randInitializeWeights(input_layer_size, hidden_layer_size)
initial_Theta2 = randInitializeWeights(hidden_layer_size, num_labels)

# Desenrrollr parametros
initial_nn_params = np.concatenate([initial_Theta1.ravel(), initial_Theta2.ravel()], axis=0)

Inicialización de parámetros de redes neuronales...


In [95]:
## Calculo de Thetas

# Después de haber completado la tarea, cambie el maxiter a uno más grande
# Usando un numero maximo de iteraciones
options= {'maxiter': 10000}

# Tratamos con diferentes valores de lambda_
lambda_ = 1

# define una función anónima (lambda) llamada costFunction.
costFunction = lambda p: nnCostFunction(p, input_layer_size,
                                        hidden_layer_size,
                                        num_labels, X_norm, y_train, lambda_)

# Ahora, costFunction es una función que toma solo un argumento.
# (los parámetros de la red neuronal)
res = optimize.minimize(costFunction,
                        initial_nn_params,
                        jac=True,
                        method='TNC',
                        options=options)

# obtenemos la solución de la optimización
nn_params = res.x

# Obtenemos Theta1 y Theta2 de nn_params
Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                    (hidden_layer_size, (input_layer_size + 1)))

Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                    (num_labels, (hidden_layer_size + 1)))

C:\Users\Manuel\AppData\Local\Temp\ipykernel_24068\3311480215.py:17: OptimizeWarning: Unknown solver options: maxiter
  res = optimize.minimize(costFunction,


In [96]:
for i in range(len(Theta1)):
    print("Thetha",i,"es: ", Theta1[i])
    print("")

Thetha 0 es:  [ 0.00689772  0.09217307 -0.09894664  0.09456197 -0.08253116 -0.08711445
  0.11437279 -0.04450613 -0.00505212 -0.1175531   0.00890481 -0.11531673
  0.10688457  0.07020571 -0.11736101  0.02390581  0.10705661  0.10275758
  0.10090868 -0.06067839  0.09995444  0.07882862  0.07559065 -0.01060503
  0.04419121 -0.05407899 -0.04315506  0.09466233 -0.01565307  0.02087181
  0.0742021   0.07451553  0.07375455 -0.10016464 -0.00884323 -0.02252134
 -0.05477311 -0.0530116   0.10681123  0.09436004  0.10992021 -0.00305563
 -0.00417708  0.07217276 -0.06573479  0.00945167  0.11387754  0.05479473
 -0.02392123  0.0857498  -0.07615058  0.08041883 -0.10939324  0.10291206
  0.0241693  -0.04186985  0.04769836  0.04822406  0.10786122]

Thetha 1 es:  [-0.08242108  0.03538628 -0.00107819  0.06568612  0.03998907 -0.05489562
  0.00638213 -0.06062198 -0.11565901 -0.08661602  0.05845594 -0.00278417
  0.08119536 -0.02928327  0.03919074 -0.03795501  0.02612297 -0.00748384
 -0.11071147  0.04570384 -0.01377

In [97]:
for i in range(len(Theta2)):
    print("Thetha",i,"es: ", Theta1[i])
    print("")

Thetha 0 es:  [ 0.00689772  0.09217307 -0.09894664  0.09456197 -0.08253116 -0.08711445
  0.11437279 -0.04450613 -0.00505212 -0.1175531   0.00890481 -0.11531673
  0.10688457  0.07020571 -0.11736101  0.02390581  0.10705661  0.10275758
  0.10090868 -0.06067839  0.09995444  0.07882862  0.07559065 -0.01060503
  0.04419121 -0.05407899 -0.04315506  0.09466233 -0.01565307  0.02087181
  0.0742021   0.07451553  0.07375455 -0.10016464 -0.00884323 -0.02252134
 -0.05477311 -0.0530116   0.10681123  0.09436004  0.10992021 -0.00305563
 -0.00417708  0.07217276 -0.06573479  0.00945167  0.11387754  0.05479473
 -0.02392123  0.0857498  -0.07615058  0.08041883 -0.10939324  0.10291206
  0.0241693  -0.04186985  0.04769836  0.04822406  0.10786122]

Thetha 1 es:  [-0.08242108  0.03538628 -0.00107819  0.06568612  0.03998907 -0.05489562
  0.00638213 -0.06062198 -0.11565901 -0.08661602  0.05845594 -0.00278417
  0.08119536 -0.02928327  0.03919074 -0.03795501  0.02612297 -0.00748384
 -0.11071147  0.04570384 -0.01377

## Funcion para realizar predicciones

Predecir la salida de una entrada dada una red neuronal entrenada, Genera la salida prevista de X dados los pesos entrenados de un neural

In [98]:
def predict(Theta1, Theta2, X):

    # Compute the output using the trained weights
    h1 = np.dot(np.concatenate([np.ones((X.shape[0], 1)), X], axis=1), Theta1.T)
    output = np.dot(np.concatenate([np.ones((h1.shape[0], 1)), h1], axis=1), Theta2.T)

    return output

In [99]:
#Creamos la matriz con 6 ejemplos para hacer la prueba predecir un precio de cada ejemplo:

# Supongamos que tienes tus datos de prueba en una variable llamada X_test
# X_test debe contener los mismos tipos de características que utilizaste para entrenar tu modelo
# Normaliza los datos de prueba utilizando mu y sigma calculados previamente
X_test_normalized = (X_test - mu) / sigma

# Calcula las predicciones para los datos de prueba
predicciones = predict(Theta1, Theta2, X_test_normalized)

# Imprime las predicciones
print("Las predicciones para los datos de prueba son:")
for i in range(len(X_test)):
    print("Para el ejemplo ", i+1, " es:", predicciones[i])
    print("")



Las predicciones para los datos de prueba son:
Para el ejemplo  1  es: [ 0.03528969 -0.02267964  0.08606047 -0.17507653 -0.03452739 -0.24243824]

Para el ejemplo  2  es: [ 0.09738966 -0.10525736  0.11474203 -0.08586016 -0.01496303 -0.03885458]

Para el ejemplo  3  es: [ 0.16560013  0.04974468  0.04679299 -0.01027123  0.01120355 -0.09155991]

Para el ejemplo  4  es: [ 0.17693294  0.19258444 -0.00361454  0.04783708 -0.01256938 -0.04201062]

Para el ejemplo  5  es: [ 0.21502653  0.03472737  0.10568027 -0.04486666 -0.00643499 -0.0991083 ]

Para el ejemplo  6  es: [ 0.07027357 -0.02172677  0.08580655  0.01914144 -0.15130686  0.13496285]

Para el ejemplo  7  es: [ 0.26331291 -0.1131191  -0.00026638 -0.11508474 -0.10575395 -0.14073949]

Para el ejemplo  8  es: [ 0.10006281 -0.09758014  0.10170328 -0.20895244 -0.10344542 -0.17111784]

Para el ejemplo  9  es: [ 0.02172874  0.00623563  0.06847268  0.0993397  -0.05517789  0.07265127]

Para el ejemplo  10  es: [-0.10292378 -0.13845114  0.18716653 

## Validaciones

In [100]:
#Para hacer las validaciones correspondientes, primero se crea la funcion del **Mean squeared error**

#haciendo calculo del error cuadratico medio:
def mean_squared_error(y_pred, y_actual):
    resta = y_pred - y_actual
    err_cuadrado = np.sum(resta ** 2)
    return err_cuadrado / len(y_pred)

In [101]:
# realiza la normalización de los datos de prueba
X_test = (X_test - mu)/ sigma


#Predicción Usando la Red Neuronal
pred = predict(Theta1, Theta2, X_test)

print(pred)

[[ 3.52896895e-02 -2.26796409e-02  8.60604711e-02 -1.75076532e-01
  -3.45273869e-02 -2.42438242e-01]
 [ 9.73896563e-02 -1.05257358e-01  1.14742027e-01 -8.58601600e-02
  -1.49630279e-02 -3.88545840e-02]
 [ 1.65600129e-01  4.97446759e-02  4.67929859e-02 -1.02712298e-02
   1.12035483e-02 -9.15599061e-02]
 ...
 [-1.27843890e-02  2.05163399e-02  1.60909619e-01 -2.42887345e-01
   6.90798654e-02 -3.61961209e-01]
 [ 3.10852247e-01  1.85828831e-01  6.55225972e-05 -2.51781622e-02
  -4.15702519e-02 -1.05379864e-01]
 [ 2.01508702e-01  4.47049844e-02  7.32791509e-02 -7.68332127e-02
  -1.09398242e-01  6.29218760e-02]]


In [107]:

X_test = (X_test - mu)/ sigma

pred = predict(Theta1, Theta2, X_test)
print(pred)

for i in range(30):
    print(f"Prediccion: {pred[i]}, Real: {y_test[i]}")

[[-0.07351792 -0.2964191   0.11629044 -0.1474606  -0.03649952 -0.15906408]
 [ 0.04189288 -0.05420779  0.16318136 -0.11713597 -0.03210435 -0.04999235]
 [ 0.18749062  0.02406559 -0.00382427 -0.03322095 -0.10039906 -0.09590622]
 ...
 [ 0.14093488  0.10219788  0.15873666  0.02861523  0.01002724  0.10376495]
 [ 0.10863619 -0.09303553  0.08803491 -0.01537836 -0.0676472   0.05234217]
 [ 0.14632763  0.11167262  0.10416723 -0.0058424   0.0269725  -0.08545197]]
Prediccion: [-0.07351792 -0.2964191   0.11629044 -0.1474606  -0.03649952 -0.15906408], Real: 3
Prediccion: [ 0.04189288 -0.05420779  0.16318136 -0.11713597 -0.03210435 -0.04999235], Real: 4
Prediccion: [ 0.18749062  0.02406559 -0.00382427 -0.03322095 -0.10039906 -0.09590622], Real: 5
Prediccion: [ 0.01627966 -0.11246521  0.18092375 -0.20888448 -0.09040369 -0.02915923], Real: 2
Prediccion: [ 0.10050886  0.06300081  0.05181026 -0.02124505 -0.02043152 -0.11167105], Real: 2
Prediccion: [ 0.15412679 -0.00423754  0.01387884 -0.04597204  0.05248

In [108]:
print('Precisión de entrenamiento: {:.2f} %'.format(np.mean(pred == y_test) * 100))

ValueError: operands could not be broadcast together with shapes (3200,6) (3200,) 